
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ADDR:http://localhost:8761/eureka/}

management:
  endpoints:
    # To expose all management endpoints
    web.exposure.include: "*"
    # To expose defined endpoints
    # web.exposure.include: health, caches, env, info, logfile, httptrace, metrics
    web.base-path: /actuator
    web.enable.include: health
  endpoint:
    health:
      show-details: ALWAYS

# http://localhost:7778/swagger-ui/index.html
app:
  openapi:
    dev-url: http://129.0.0.129:${server.port}
    homol-url: http://129.0.0.129:${server.port}
    prod-url: https://prod-foo.com
