# http://localhost:7775/swagger-ui/index.html
springdoc:
  #api-docs:
  #  path: /api-docs
  #swagger-ui:
  #  path: /swagger-ui/index.html

app:
  openapi:
    dev-url: http://localhost:${server.port}
    homol-url: http://10.0.0.129:${server.port}
    prod-url: https://prod-foo.com
