#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false
#springdoc.packages-to-scan=com.chj.gr.controller
springdoc:
  swagger-ui:
    path: /jihed-koder-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /jihed-koder-documentation
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha

app:
  openapi:
    dev-url: http://localhost:${server.port}
    homol-url: http://10.0.0.129:${server.port}
    prod-url: https://prod-bar.com

spring:
  cloud:
    vault:
      scheme: http
      uri: http://container-vault-server:8200
      token: my-root-token
      authentication: TOKEN
      connection-timeout: 5000
      read-timeout: 15000
      kv:
        enabled: true
        default-context: z-springboot-bar-service
      import: vault://